[package]
name = "daft-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Core VCS engine for Draft: SHA-256 CAS, binary index, refs, and objects"

[dependencies]
sha2 = { workspace = true }
hex = { workspace = true }
flate2 = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
tempfile = { workspace = true }
libc = { workspace = true }
memmap2 = { workspace = true }
walkdir = { workspace = true }
chrono = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
